resources:
  - ai.service-backend.yaml
  - gateway.yaml
  - authconfig.yaml
  - gateway-class.yaml
  - backend.yaml
  - ai.gateway-route.yaml
  - backend-security-policy.yaml
  - authorino.yaml
  - backend-tls-policy.yaml
  - security-policy.yaml