apiVersion: operator.authorino.kuadrant.io/v1beta1
kind: Authorino
metadata:
  name: converse
  namespace: converse-llm
spec:
  listener:
    tls:
      enabled: false
  oidcServer:
    tls:
      enabled: false