apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: converse-authorino-security-policy
  namespace: converse-llm
spec:
  targetSelectors:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
  extAuth:
    grpc:
      backendRefs:
        - group: ''
          name: converse-authorino-authorization
          namespace: converse-llm
          port: 50051
          kind: Service
          weight: 1