annotations:
  artifacthub.io/changes: |-
    - kind: added
      description: |-
        Add support for named route rules.
    - kind: added
      description: |-
        Allow creating PodDisruptionBudget Objects for controllers.
    - kind: added
      description: |-
        Allow defining experimental CORS and externalAuth filters in HTTPRoutes.
apiVersion: v2
description: Function library for Helm charts
home: https://github.com/bjw-s-labs/helm-charts/tree/main/charts/library/common
keywords:
- common
- library
kubeVersion: '>=1.28.0-0'
maintainers:
- email: me@bjw-s.dev
  name: bjw-s
name: common
sources:
- https://github.com/bjw-s-labs/helm-charts
type: library
version: 4.5.0
